# Generated by Django 3.1.4 on 2021-06-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Login_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_13', models.CharField(help_text='หมายเลขบัตรประจำตัวประชาชน', max_length=13, null=True)),
                ('login_Date', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.CharField(max_length=10, null=True)),
                ('EXID', models.CharField(max_length=5, null=True)),
                ('ID13', models.CharField(max_length=13, null=True)),
                ('BDD', models.DateField()),
                ('FirstName', models.CharField(max_length=13, null=True)),
                ('LastName', models.CharField(max_length=13, null=True)),
                ('Nation', models.CharField(max_length=1, null=True)),
                ('Religion', models.CharField(max_length=11, null=True)),
                ('LProvice', models.CharField(max_length=2, null=True)),
                ('Asec', models.CharField(max_length=1, null=True)),
                ('Area', models.CharField(max_length=2, null=True)),
                ('QUA', models.CharField(max_length=1, null=True)),
                ('education', models.CharField(choices=[('m4', 'ม4'), ('m5', 'ม5'), ('m6', 'ม6'), ('mx', 'อื่นๆ')], default='mx', max_length=2)),
                ('SchPro', models.CharField(max_length=2, null=True)),
                ('SchName', models.CharField(max_length=100, null=True)),
                ('GPA', models.CharField(max_length=4, null=True)),
                ('S_tel', models.CharField(max_length=10, null=True)),
                ('F_FName', models.CharField(max_length=50, null=True)),
                ('F_LName', models.CharField(max_length=50, null=True)),
                ('F_ID13', models.CharField(max_length=13, null=True)),
                ('F_Stat', models.CharField(max_length=1, null=True)),
                ('F_Pro', models.CharField(max_length=2, null=True)),
                ('F_Minis', models.CharField(max_length=2, null=True)),
                ('F_Tel', models.CharField(max_length=10, null=True)),
                ('M_FName', models.CharField(max_length=50, null=True)),
                ('M_LName', models.CharField(max_length=50, null=True)),
                ('M_ID13', models.CharField(max_length=13, null=True)),
                ('M_Stat', models.CharField(max_length=1, null=True)),
                ('M_Pro', models.CharField(max_length=2, null=True)),
                ('M_Minis', models.CharField(max_length=2, null=True)),
                ('M_Tel', models.CharField(max_length=10, null=True)),
                ('AD1', models.CharField(max_length=1, null=True)),
                ('AD2', models.CharField(max_length=1, null=True)),
                ('AD3', models.CharField(max_length=1, null=True)),
                ('AD4', models.CharField(max_length=1, null=True)),
                ('AD5', models.CharField(max_length=1, null=True)),
                ('STAT', models.CharField(max_length=2, null=True)),
                ('DateREC', models.DateTimeField(null=True)),
                ('DatePrintForm', models.DateTimeField(null=True)),
                ('DatePAY', models.DateTimeField(null=True)),
                ('AID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pca65.login_log')),
            ],
        ),
    ]
